---
# title: "Template Title"
# author: "Your Name"
# date: "The Date"
output: pdf_document
header-includes: 
  - \usepackage{amsmath}
  - \usepackage{caption}
  - \thispagestyle{empty}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\begin{center}
Decomposition.
\end{center}
\[
\begin{gathered} \begin{bmatrix}
y_{1, t} \\
y_{2, t} \\
\end{bmatrix} = \begin{bmatrix}
\mu_{1} \\
\mu_{2} \\
\end{bmatrix}
+
\begin{bmatrix}
y_{1, t}^w \\
y_{2, t}^w \\
\end{bmatrix} \end{gathered}
\]
\vspace{1em}
\begin{center} Within-model. \end{center} \[
\begin{gathered} \begin{bmatrix}
y_{1, t}^w \\
y_{2, t}^w \\
\end{bmatrix} = \begin{bmatrix} \phi_{11(1)} & 
\phi_{21(1)} \\
\phi_{12(1)} & 
\phi_{22(1)} \\ \end{bmatrix} \begin{bmatrix} y_{1, t - 1}^w \\
y_{2, t - 1}^w \\ \end{bmatrix} + \begin{bmatrix} \zeta_{1, t} \\
\zeta_{2, t} \\ \end{bmatrix} ,\\ 
\text{with}~
  \zeta_{y, i} \sim \mathit{MVN}(\mathbf{0}, \mathbf{\Psi}) \end{gathered}
\]
\vspace{1em}
\begin{center} Between-model. \end{center} \[
\begin{gathered} \begin{bmatrix} \mu_{1,i}\\
\mu_{2,i}\\
\phi_{11;(1),i}\\
\phi_{12;(1),i}\\
\phi_{21;(1),i}\\
\phi_{22;(1),i}\\
\log(\pi_{1,i})\\
\log(\pi_{2,i})\\ \end{bmatrix} = \begin{bmatrix} \gamma_{0,\mu_{1}}\\
\gamma_{0,\mu_{2}}\\
\gamma_{0,\phi_{11;(1)}}\\
\gamma_{0,\phi_{12;(1)}}\\
\gamma_{0,\phi_{21;(1)}}\\
\gamma_{0,\phi_{22;(1)}}\\
\gamma_{0,\log(\pi_{1})}\\
\gamma_{0,\log(\pi_{2})}\\ \end{bmatrix} +
  \begin{bmatrix} \upsilon_{\mu_{1},i}\\
\upsilon_{\mu_{2},i}\\
\upsilon_{\phi_{11;(1)},i}\\
\upsilon_{\phi_{12;(1)},i}\\
\upsilon_{\phi_{21;(1)},i}\\
\upsilon_{\phi_{22;(1)},i}\\
\upsilon_{\log(\pi_{1}),i}\\
\upsilon_{\log(\pi_{2}),i}\\ \end{bmatrix} ,\\ 
\text{with}~
  \upsilon_{i} \sim \mathit{MVN}(\mathbf{0}, \mathbf{\Omega}) \\
 \begin{bmatrix} y\\
y2\\ \end{bmatrix} = \begin{bmatrix} \gamma_{1,y} & \gamma_{2,y} & \gamma_{3,y} & \gamma_{4,y} & \gamma_{5,y} & \gamma_{6,y} & \gamma_{7,y} & \gamma_{8,y}\\
\gamma_{1,y2} & \gamma_{2,y2} & \gamma_{3,y2} & \gamma_{4,y2} & \gamma_{5,y2} & \gamma_{6,y2} & \gamma_{7,y2} & \gamma_{8,y2} \end{bmatrix} \begin{bmatrix} \mu_{1}\\
\mu_{2}\\
\phi_{11;(1)}\\
\phi_{12;(1)}\\
\phi_{21;(1)}\\
\phi_{22;(1)}\\
\log(\pi_{1})\\
\log(\pi_{2}) \end{bmatrix} + \begin{bmatrix} \varepsilon_{y}\\
\varepsilon_{y2}\\ \end{bmatrix} \end{gathered}
\]
\vspace{1em}
