---
# title: "Template Title"
# author: "Your Name"
# date: "The Date"
output: pdf_document
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
  - \pgfplotsset{compat=1.18}
  - \usetikzlibrary{shapes, positioning, calc}
  - \newlength{\Radius}
  - \setlength\Radius{15mm}
  - \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{tikzpicture}[
  auto, > = latex, align=center,
	latent/.style = {circle, draw, thick, inner sep = 2pt, minimum width = \Radius},
	intercept/.style = {regular polygon,regular polygon sides = 3, draw, thick, inner sep = 0pt, minimum size = \Radius},
	manifest/.style = {rectangle, draw, thick, inner sep = 0pt, minimum size = 5mm, node distance = 4.5mm},
	mean/.style = {regular polygon, regular polygon sides = 3, draw, thick, inner sep = 0pt, minimum size = 8mm},
	paths/.style = {arrows = ->, thick, > = {stealth[]}},
	error/.style = {circle, draw = none, fill = none, thick, inner sep = 0pt, minimum size = 5mm},
	variance/.style = {<->, thick, > = {stealth[]}, bend right = 270, looseness = 2},
	cov/.style = {<->, thick, > = {stealth[]}, bend right = 290},
	]

  % draw within-level structural model
  \node [latent] (y1wt-1)                        {$y_{1,t-1}^w$};
  \node [latent] (y1wt)    [right = of y1wt-1]   {$y_{1,t}^w$};
  \node [latent] (eps1t)   [right = of y1wt]     {$\delta_{{y_1},t}$};

  % draw paths
  \draw [paths]  (y1wt-1)  to node [] {$\phi_{y_1}$}  (y1wt);
  \draw [paths]  (eps1t)   to node [] {}           (y1wt);

  % draw (co-)variances
  \draw [cov]	  (eps1t.north east)   to node [] {} (eps1t.south east);
\end{tikzpicture}
