---
# title: "Template Title"
# author: "Your Name"
# date: "The Date"
output: pdf_document
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
  - \pgfplotsset{compat=1.18}
  - \usetikzlibrary{shapes, positioning, calc, decorations.markings, chains, scopes}
  - \newlength{\Radius}
  - \setlength\Radius{4em}
  - \usepackage{amsmath}
  - \usepackage{caption}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



\begin{figure}
\centering
\caption*{Decomposition.}
\begin{tikzpicture}[
    auto, > = latex, align=center,
  	latent/.style = {
  	  circle, draw, thick, inner sep = 2pt, minimum width = \Radius
  	},
  	manifest/.style = {
  	  rectangle, draw, thick, inner sep = 0pt, minimum size = \Radius/2
  	},
  	intercept/.style = {
  	  regular polygon,regular polygon sides = 3, draw, thick,
  	  inner sep = 0pt, minimum size = \Radius
  	},
  	mean/.style = {
  	  regular polygon, regular polygon sides = 3, draw, thick,
  	  inner sep = 0pt, minimum size = 8mm
  	},
  	path/.style = {
  	  arrows = ->, thick, > = {stealth[]}
  	},
  	error/.style = {
  	  circle, draw = none, fill = none, thick,
  	  inner sep = 0pt, minimum size = 5mm
  	},
  	var/.style = {
  	  <->, thick, > = {stealth[]}, bend right = 270, looseness = 2
  	},
  	cov/.style = {
  	  <->, thick, > = {stealth[]}, bend right = 300
  	},
  	% style to add a circle in the middle of a path
    random/.style = {
      postaction = {
        decorate, decoration = {
          markings,
          mark = at position .5 with {
            \draw[fill = black] circle[radius = 2pt];
          }
        }
      }
    },
    random_cl/.style = {
      postaction = {decorate, decoration = {
        markings,
        mark = at position .2 with {
          \draw[fill = black] circle[radius = 2pt];}
        }
      }
    },
  	]

    % draw decomposition
    \node  [manifest]  (y1t)  {$y_{1,t}$};
    \node  [latent]  (y1wt)  [above = 2.5em of y1t]  {$y_{1,t}^w$};
    \node  [latent]  (mu_1)  [below = 2.5em of y1t]  {$\mu_{1}$};

    % draw nodes
    \foreach \i [remember = \i as \lasti (initially 1)] in {2, ..., 3}
    \node  [manifest]  (y\i t)  [right = 2.5em of y\lasti t]  {$y_{\i,t}$};

    \foreach \i [remember = \i as \lasti (initially 1)] in {2, ..., 3}
    \node  [latent]  (y\i wt)  [above = 2.5em of y\i t]  {$y_{\i,t}^w$};

    \foreach \i [remember = \i as \lasti (initially 1)] in {2, ...,3}
    \node  [latent]  (mu_\i)  [below = 2.5em of y\i t]  {$\mu_{\i}$};

    % draw paths
    \foreach \i [remember = \i as \lasti (initially 1)] in {1, ...,3}
    \draw  [path]  (y\i wt)  to node  []  {}  (y\i t);

    \foreach \i [remember = \i as \lasti (initially 1)] in {1, ...,3}
    \draw  [path]  (mu_\i)  to node  []  {}  (y\i t);
    
\end{tikzpicture}
\end{figure}

\begin{figure}
\centering
\caption*{Within-model.}
\begin{tikzpicture}[
    auto, > = latex, align=center,
  	latent/.style = {
  	  circle, draw, thick, inner sep = 2pt, minimum width = \Radius
  	},
  	manifest/.style = {
  	  rectangle, draw, thick, inner sep = 0pt, minimum size = \Radius/2
  	},
  	intercept/.style = {
  	  regular polygon,regular polygon sides = 3, draw, thick,
  	  inner sep = 0pt, minimum size = \Radius
  	},
  	mean/.style = {
  	  regular polygon, regular polygon sides = 3, draw, thick,
  	  inner sep = 0pt, minimum size = 8mm
  	},
  	path/.style = {
  	  arrows = ->, thick, > = {stealth[]}
  	},
  	error/.style = {
  	  circle, draw = none, fill = none, thick,
  	  inner sep = 0pt, minimum size = 5mm
  	},
  	var/.style = {
  	  <->, thick, > = {stealth[]}, bend right = 270, looseness = 2
  	},
  	cov/.style = {
  	  <->, thick, > = {stealth[]}, bend right = 300
  	},
  	% style to add a circle in the middle of a path
    random/.style = {
      postaction = {
        decorate, decoration = {
          markings,
          mark = at position .5 with {
            \draw[fill = black] circle[radius = 2pt];
          }
        }
      }
    },
    random_cl/.style = {
      postaction = {decorate, decoration = {
        markings,
        mark = at position .2 with {
          \draw[fill = black] circle[radius = 2pt];}
        }
      }
    },
  	]

    % draw within-level structural model
    \node  [latent]  (y1wt-1)  {$y_{1,t-1}^w$};
    \node  [latent]  (y1wt)  [right =5em of y1wt-1]  {$y_{1,t}^w$};
    \node  [latent]  (delta1t)  [right =2.5em of y1wt]  {$\delta_{1,t}$};

    % draw nodes
    \foreach \i [remember = \i as \lasti (initially 1)] in {2, ..., 3}
    \node  [latent]  (y\i wt-1)  [below = 2.5em of y\lasti wt-1]  {$y_{\i ,t-1}^w$};

    \foreach \i [remember = \i as \lasti (initially 1)] in {2, ..., 3}
    \node  [latent]  (y\i wt)  [below = 2.5em of y\lasti wt]  {$y_{\i ,t}^w$};

    \foreach \i [remember = \i as \lasti (initially 1)] in {2, ..., 3}
    \node  [latent]  (delta\i t)  [below = 2.5em of delta\lasti t]  {$\delta_{\i ,t}$};

    % draw paths from residuals to yiwt
    \foreach \i [remember = \i as \lasti (initially 1)] in {1, ...,3}
    \draw  [path]  (delta\i t)  to node  []  {}  (y\i wt);
    
\draw  [path, postaction = random]  (y1wt-1)  to node  []  {$\phi_{11}$}  (y1wt);
\draw  [path, postaction = random_cl]  (y1wt-1)  to node  [pos = .2]  {$\phi_{12}$}  (y2wt);
\draw  [path, postaction = random_cl]  (y1wt-1)  to node  [pos = .2]  {$\phi_{13}$}  (y3wt);
\draw  [path, postaction = random_cl]  (y2wt-1)  to node  [pos = .2]  {$\phi_{21}$}  (y1wt);
\draw  [path, postaction = random]  (y2wt-1)  to node  []  {$\phi_{22}$}  (y2wt);
\draw  [path, postaction = random_cl]  (y2wt-1)  to node  [pos = .2]  {$\phi_{23}$}  (y3wt);
\draw  [path, postaction = random_cl]  (y3wt-1)  to node  [pos = .2]  {$\phi_{31}$}  (y1wt);
\draw  [path, postaction = random_cl]  (y3wt-1)  to node  [pos = .2]  {$\phi_{32}$}  (y2wt);
\draw  [path, postaction = random]  (y3wt-1)  to node  []  {$\phi_{33}$}  (y3wt);

\draw  [var, postaction = random]  (delta1t.120)  to node  []  {$\pi_{1}$}  (delta1t.60);
 \draw  [cov, postaction = random]  (delta1t.0)  to node  []  {$\pi_{12}$}  (delta2t.0);
\draw  [var, postaction = random]  (delta2t.120)  to node  []  {$\pi_{2}$}  (delta2t.60);
 \draw  [cov, postaction = random]  (delta1t.0)  to node  []  {$\pi_{13}$}  (delta3t.0);
\draw  [var, postaction = random]  (delta3t.120)  to node  []  {$\pi_{3}$}  (delta3t.60);
 \draw  [cov, postaction = random]  (delta2t.0)  to node  []  {$\pi_{23}$}  (delta3t.0);

\end{tikzpicture}
\end{figure}

\begin{figure}
\centering
\caption*{Between-model.}
\begin{tikzpicture}[
    auto, > = latex, align=center,
  	latent/.style = {
  	  circle, draw, thick, inner sep = 2pt, minimum width = \Radius
  	},
  	manifest/.style = {
  	  rectangle, draw, thick, inner sep = 0pt, minimum size = \Radius/2
  	},
  	intercept/.style = {
  	  regular polygon,regular polygon sides = 3, draw, thick,
  	  inner sep = 0pt, minimum size = \Radius
  	},
  	mean/.style = {
  	  regular polygon, regular polygon sides = 3, draw, thick,
  	  inner sep = 0pt, minimum size = 8mm
  	},
  	path/.style = {
  	  arrows = ->, thick, > = {stealth[]}
  	},
  	error/.style = {
  	  circle, draw = none, fill = none, thick,
  	  inner sep = 0pt, minimum size = 5mm
  	},
  	var/.style = {
  	  <->, thick, > = {stealth[]}, bend right = 270, looseness = 2
  	},
  	cov/.style = {
  	  <->, thick, > = {stealth[]}, bend right = 300
  	},
  	% style to add a circle in the middle of a path
    random/.style = {
      postaction = {
        decorate, decoration = {
          markings,
          mark = at position .5 with {
            \draw[fill = black] circle[radius = 2pt];
          }
        }
      }
    },
    random_cl/.style = {
      postaction = {decorate, decoration = {
        markings,
        mark = at position .2 with {
          \draw[fill = black] circle[radius = 2pt];}
        }
      }
    },
  	]
\node  [latent]  (mu_1)  {$\mu_{1}$};
\node  [latent]  (mu_2)  [right = 1em of mu_1]  {$\mu_{2}$};
\node  [latent]  (mu_3)  [right = 1em of mu_2]  {$\mu_{3}$};
\node  [latent]  (phi_11)  [right = 1em of mu_3]  {$\phi_{11}$};
\node  [latent]  (phi_12)  [right = 1em of phi_11]  {$\phi_{12}$};
\node  [latent]  (phi_13)  [right = 1em of phi_12]  {$\phi_{13}$};
\node  [latent]  (phi_21)  [right = 1em of phi_13]  {$\phi_{21}$};
\node  [latent]  (phi_22)  [right = 1em of phi_21]  {$\phi_{22}$};
\node  [latent]  (phi_23)  [right = 1em of phi_22]  {$\phi_{23}$};
\node  [latent]  (phi_31)  [right = 1em of phi_23]  {$\phi_{31}$};
\node  [latent]  (phi_32)  [right = 1em of phi_31]  {$\phi_{32}$};
\node  [latent]  (phi_33)  [right = 1em of phi_32]  {$\phi_{33}$};
\node  [latent]  (lnsigma2_1)  [right = 1em of phi_33]  {$\log(\pi_{1})$};
\node  [latent]  (lnsigma2_2)  [right = 1em of lnsigma2_1]  {$\log(\pi_{2})$};
\node  [latent]  (lnsigma2_3)  [right = 1em of lnsigma2_2]  {$\log(\pi_{3})$};
\node  [latent]  (lnsigma_12)  [right = 1em of lnsigma2_3]  {$\log(\pi_{12})$};
\node  [latent]  (lnsigma_13)  [right = 1em of lnsigma_12]  {$\log(\pi_{13})$};
\node  [latent]  (lnsigma_23)  [right = 1em of lnsigma_13]  {$\log(\pi_{23})$};

\draw  [cov]  (mu_1.north)  to node  []  {}  (mu_2.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (mu_3.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (phi_11.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (phi_12.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (phi_13.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (phi_21.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (phi_22.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (phi_23.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (phi_31.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (phi_32.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (mu_1.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (mu_3.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (phi_11.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (phi_12.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (phi_13.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (phi_21.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (phi_22.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (phi_23.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (phi_31.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (phi_32.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (mu_2.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (phi_11.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (phi_12.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (phi_13.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (phi_21.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (phi_22.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (phi_23.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (phi_31.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (phi_32.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (mu_3.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (phi_12.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (phi_13.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (phi_21.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (phi_22.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (phi_23.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (phi_31.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (phi_32.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (phi_11.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (phi_13.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (phi_21.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (phi_22.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (phi_23.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (phi_31.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (phi_32.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (phi_12.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (phi_21.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (phi_22.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (phi_23.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (phi_31.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (phi_32.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (phi_13.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (phi_22.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (phi_23.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (phi_31.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (phi_32.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (phi_21.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (phi_22.north)  to node  []  {}  (phi_23.north);
\draw  [cov]  (phi_22.north)  to node  []  {}  (phi_31.north);
\draw  [cov]  (phi_22.north)  to node  []  {}  (phi_32.north);
\draw  [cov]  (phi_22.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (phi_22.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (phi_22.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (phi_22.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (phi_22.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (phi_22.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (phi_22.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (phi_23.north)  to node  []  {}  (phi_31.north);
\draw  [cov]  (phi_23.north)  to node  []  {}  (phi_32.north);
\draw  [cov]  (phi_23.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (phi_23.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (phi_23.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (phi_23.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (phi_23.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (phi_23.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (phi_23.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (phi_31.north)  to node  []  {}  (phi_32.north);
\draw  [cov]  (phi_31.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (phi_31.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (phi_31.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (phi_31.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (phi_31.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (phi_31.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (phi_31.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (phi_32.north)  to node  []  {}  (phi_33.north);
\draw  [cov]  (phi_32.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (phi_32.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (phi_32.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (phi_32.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (phi_32.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (phi_32.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (phi_33.north)  to node  []  {}  (lnsigma2_1.north);
\draw  [cov]  (phi_33.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (phi_33.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (phi_33.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (phi_33.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (phi_33.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (lnsigma2_1.north)  to node  []  {}  (lnsigma2_2.north);
\draw  [cov]  (lnsigma2_1.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (lnsigma2_1.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (lnsigma2_1.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (lnsigma2_1.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (lnsigma2_2.north)  to node  []  {}  (lnsigma2_3.north);
\draw  [cov]  (lnsigma2_2.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (lnsigma2_2.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (lnsigma2_2.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (lnsigma2_3.north)  to node  []  {}  (lnsigma_12.north);
\draw  [cov]  (lnsigma2_3.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (lnsigma2_3.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (lnsigma_12.north)  to node  []  {}  (lnsigma_13.north);
\draw  [cov]  (lnsigma_12.north)  to node  []  {}  (lnsigma_23.north);
\draw  [cov]  (lnsigma_13.north)  to node  []  {}  (lnsigma_23.north);

\end{tikzpicture}
\end{figure}
